# Generated by Django 5.2 on 2025-05-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='title',
            field=models.CharField(blank=True, null=True),
        ),
    ]
