# Generated by Django 5.2 on 2025-05-29 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_collection_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 29, 7, 22, 31, 879507, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
