# Generated by Django 5.2 on 2025-05-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_tag_article_language_article_tags'),
        ('journal', '0003_collection_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='articles',
            field=models.ManyToManyField(to='articles.article'),
        ),
    ]
