# Generated by Django 5.2 on 2025-04-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bids',
            field=models.ManyToManyField(blank=True, null=True, to='bid.bid'),
        ),
    ]
