# Generated by Django 5.2 on 2025-04-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('АВТОР', 'АВТОР'), ('РЕДАКТОР', 'РЕДАКТОР'), ('РЕЦЕНЗИСТ', 'РЕЦЕНЗИСТ')], default='АВТОР', max_length=255),
        ),
    ]
