# Generated by Django 5.2 on 2025-05-28 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bids',
        ),
    ]
