# Generated by Django 5.2 on 2025-04-10 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 10, 11, 31, 39, 467613, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
