# Generated by Django 5.2 on 2025-05-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
