# Generated by Django 5.2 on 2025-05-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_title_kk_article_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='annotation_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='annotation_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
