# Generated by Django 5.2 on 2025-05-27 12:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_category_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='annotation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='annotation_kk',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='annotation_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
