# Generated by Django 5.2 on 2025-05-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_annotation_alter_article_annotation_kk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('Русский', 'Ru'), ('Казахский', 'Kz'), ('Английский', 'Eng')], default='Русский'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='articles.tag'),
        ),
    ]
