# Generated by Django 5.2 on 2025-05-30 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_tag_article_language_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(default=datetime.datetime(2025, 5, 30, 11, 41, 13, 146720, tzinfo=datetime.timezone.utc), upload_to='articles/'),
            preserve_default=False,
        ),
    ]
