# Generated by Django 5.2 on 2025-05-28 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 28, 11, 48, 52, 537167, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
