# Generated by Django 5.2 on 2025-04-08 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('status', models.CharField(choices=[('Черновик', 'Черновик'), ('Отправлено', 'Отправлено'), ('На проверке у редактора', 'На проверке у редактора'), ('Отправлено на рецензию', 'Отправлено на рецензию'), ('Требуется доработка', 'Требуется доработка'), ('Повторная рецензия', 'Повторная рецензия'), ('Принято к публикации', 'Принято к публикации'), ('Отклонено', 'Отклонено'), ('Опубликовано', 'Опубликовано')], default={'На проверке у редактора': 'На проверке у редактора', 'Опубликовано': 'Опубликовано', 'Отклонено': 'Отклонено', 'Отправлено': 'Отправлено', 'Отправлено на рецензию': 'Отправлено на рецензию', 'Повторная рецензия': 'Повторная рецензия', 'Принято к публикации': 'Принято к публикации', 'Требуется доработка': 'Требуется доработка', 'Черновик': 'Черновик'}, max_length=255)),
                ('title', models.TextField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
