# Generated by Django 5.2 on 2025-05-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0003_alter_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='authors_confirmed',
            field=models.BooleanField(default=False, help_text='Все авторы подтвердили прочтение и согласие с рукописью'),
        ),
        migrations.AddField(
            model_name='bid',
            name='exclusive_submission',
            field=models.BooleanField(default=True, help_text='Подтвердите, что статья не публиковалась ранее и не рассматривается другим журналом'),
        ),
        migrations.AddField(
            model_name='bid',
            name='no_plagiarism',
            field=models.BooleanField(default=True, help_text='Подтвердите, что в статье отсутствуют неправомерные заимствования текста (плагиат)'),
        ),
    ]
