# Generated by Django 5.2 on 2025-05-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0004_bid_authors_confirmed_bid_exclusive_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='title_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='title_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
