# Generated by Django 5.2 on 2025-05-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0005_bid_title_kk_bid_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='ai_usage_details',
            field=models.TextField(blank=True, help_text='Если применялся ИИ, опишите, на каких этапах (поиск источников, анализ данных, визуализация и т.п.)', null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='authors_file',
            field=models.FileField(blank=True, help_text='Файл со сведениями об авторах в формате *.DOC или *.DOCX. Перед загрузкой убедитесь, что файл оформлен в соответствии с <a href="URL_на_требования" target="_blank">требованиями для авторов</a> и включает:<br>– Ф. И. О. авторов, их аффилиации (название подразделения, организация, город, страна), ученые степени, звания, ORCID;<br>– информацию для корреспонденции: Ф. И. О., email, номер телефона;<br>– информацию об источниках финансирования;<br>– информацию о вкладе авторов (с указанием инициалов и видов вклада);<br>– иные авторские комментарии и примечания (конфликты интересов, благодарности и т.п.).', null=True, upload_to='authors_files/'),
        ),
        migrations.AddField(
            model_name='bid',
            name='cover_letter',
            field=models.FileField(blank=True, help_text='Файл с заполненным и подписанным всеми авторами письмом в формате *.PDF. Перед загрузкой убедитесь, что файл оформлен в соответствии с <a href="URL_на_требования" target="_blank">требованиями</a>.', null=True, upload_to='cover_letters/'),
        ),
        migrations.AddField(
            model_name='bid',
            name='manuscript',
            field=models.FileField(blank=True, help_text='Файл рукописи статьи в формате *.DOC или *.DOCX. Перед загрузкой убедитесь, что файл оформлен в соответствии с <a href="URL_на_требования" target="_blank">требованиями для авторов</a> и не содержит никаких упоминаний об авторах, их местах работы, должностях, ученых степенях и ученых званиях, а также об источниках финансирования и иной информации, которая может использоваться для идентификации авторов.', null=True, upload_to='manuscripts/'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='authors_confirmed',
            field=models.BooleanField(blank=True, default=False, help_text='Все авторы подтвердили прочтение и согласие с рукописью', null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='exclusive_submission',
            field=models.BooleanField(blank=True, default=True, help_text='Подтвердите, что статья не публиковалась ранее и не рассматривается другим журналом', null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='no_plagiarism',
            field=models.BooleanField(blank=True, default=True, help_text='Подтвердите, что в статье отсутствуют неправомерные заимствования текста (плагиат)', null=True),
        ),
    ]
