# Generated by Django 5.2 on 2025-05-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0006_bid_ai_usage_details_bid_authors_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='title',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='title_kk',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='title_ru',
        ),
    ]
