# Generated by Django 5.2 on 2025-05-20 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0007_remove_bid_title_remove_bid_title_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='ai_usage_details',
            field=models.TextField(default=datetime.datetime(2025, 5, 20, 7, 54, 14, 414732, tzinfo=datetime.timezone.utc), help_text='Если применялся ИИ, опишите, на каких этапах (поиск источников, анализ данных, визуализация и т.п.)'),
            preserve_default=False,
        ),
    ]
