# Generated by Django 5.2 on 2025-05-28 06:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0010_bid_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='review',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
