# Generated by Django 5.2 on 2025-05-29 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0011_bid_comment_alter_bid_review'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='journal.collection'),
        ),
    ]
