# Generated by Django 5.2 on 2025-05-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0012_bid_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='collection',
        ),
    ]
