# Generated by Django 5.2 on 2025-05-30 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_tag_article_language_article_tags'),
        ('bid', '0013_remove_bid_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_version', to='articles.article')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='bid.bid')),
            ],
        ),
    ]
